sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - PIP_DJANGO='Django>=1.8,<1.9'
  - PIP_DJANGO='Django>=1.10,<1.11'
  - PIP_DJANGO='Django>=1.11,<1.12'
install:
  - "pip install $PIP_DJANGO pyyaml coveralls pytest-django"
  - "pip install -e ."
script:
  coverage run $VIRTUAL_ENV/bin/py.test --ds=test_settings typedmodels/tests.py
after_success:
  coveralls
